files: \.(py)$
default_stages: [commit, manual]
repos:

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.9
    hooks:
    - id: ruff
      args: [
      --fix,
      --unsafe-fixes,
      --target-version, "py312",
      --select, "ALL",
      --ignore, "ANN,C90,D,E501,F401,FBT,PLR091,S101,S113,T20"
      ]
    - id: ruff-format

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
    - id: mypy
      additional_dependencies: [types-requests]
      stages: [manual]

-   repo: https://github.com/dosisod/refurb
    rev: v2.0.0
    hooks:
    - id: refurb
      args: [--python-version, "3.12"]
      stages: [manual]

